### ISSUE TITLE
git clone get some unexpected characters in MicrosoftGraph.psm1

### ISSUE THREAD

**Issue by cms0058** [Freakling/Powershell-MicrosoftGraph#1]
Had to change 'â€“' to '-' in Powershell-MicrosoftGraph\MicrosoftGraph\MicrosoftGraph.psm1
Not sure if it is due to encoding, I am in Sweden but my computer is on US settings.

ie row 70
$Response = Invoke-RestMethod -Uri $URI â€“Headers $authHeader -Method $method -ErrorAction Stop

**Comment by kms852** [comment]
I ran into that as well. The code looked fine but the PowerShell error reflected â€ in the error message. When I tried to find the cause in the code itself, there are 8 long dashes instead of the normal hyphen that prefixes arguments.

**Comment by Freakling** [comment]
replaced all '–' (https://www.fileformat.info/info/unicode/char/2013/index.htm) with '-' (https://www.fileformat.info/info/unicode/char/2212/index.htm). Not sure how that snuck in to my code.
